name: Go

on:
  push:
    tags:
      - "*"

jobs:
  release:
    strategy:
      matrix:
        goarch: [amd64, arm64, arm]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run build
      run: GOOS=linux GOARCH=${{ matrix.goarch }} go build -o traefik2unbound-${GITHUB_REF/refs\/tags\//}.$GOOS-${{ matrix.goarch }} main.go

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: traefik2unbound-*
